### ISSUE TITLE
when new tag is added it throws error

### ISSUE THREAD

**Issue by goldentigerindia** [prometheus/influxdb_exporter#20]
E.g: Consider that a data was being published in this format 

cpu_usage_guest{cpu="cpu1",host="host1"} 0

If you add a new tag say app like this 

cpu_usage_guest{app="xxx",cpu="cpu1",host="host1"} 0

the endpoint start throwing error and requires to stop and restart the application to have correct data

**Comment by matthiasr** [comment]
This behaviour comes from the Prometheus client library, which rejects metrics with mixed label sets. There is an option to make it "lenient" but that only means all the metrics with either one or the other label set will be swallowed.

We can handle this in two ways: either say "don't do that – tie the exporter lifetime to the service lifetime so you always get consistent metrics" or we expand the label sets for each metric to be the superset of all label sets.

@goldentigerindia for your use case, is the former feasible? For most exporters, the best way to run them is 1:1 with application processes and restarting them when the application restarts.

**Comment by goldentigerindia** [comment]
The error doesn't go away even after long time. The metrics will no longer be using the old structure . I am not sure how to make it lenient and get past it. 
I can use telegraf's on Prometheus exporter but that requires port to be exposed outside and ask Prometheus to read from port ( opening a port on application hosts might expose security risk). My idea was to publish the data from multiple machines to influxdb_exporter (may be running on multiple machines)  and use that endpoint to consume the data. This way you are avoiding having to change the Prometheus to fetch data from each machine. To segregate machines I added application name as global tag so that in grafana i can use that to filter the data for hosts of that application. As soon as i added the new tag it started throwing error. I think it should recreate the structure based on some interval.

**Comment by matthiasr** [comment]
You need to restart the exporter to reset the metrics / label sets.

You use case sounds like you are using telegraf and this exporter to work around the Prometheus pull model. This is not how it is meant to be used at all, and it's not a use case I want to support (since it would add a lot of complexity, and has a lot of problems).

One project that I know of for your use case is [PushProx](https://github.com/RobustPerception/PushProx). Another way I can think of is to run a Prometheus inside the network where it can scrape the targets, and then use [remote write](https://prometheus.io/docs/operating/integrations/#remote-endpoints-and-storage) to send the metrics off. Caveat here is that I don't know if Prometheus itself can actually receive that, I know that Cortex can though.

**Comment by brian-brazil** [comment]
> then use remote write to send the metrics off. Caveat here is that I don't know if Prometheus itself can actually receive that

It can't, as that'd be push.
